package main

import (
	"fmt"
	"time"

	"github.com/hyp3rd/hypercache"
)

func main() {
	hypercache, err := hypercache.NewInMemoryWithDefaults(10)

	if err != nil {
		panic(err)
	}

	type User struct {
		Name       string
		Age        int
		LastAccess time.Time
		Pass       string
		Email      string
		Phone      string
		IsAdmin    bool
		IsGuest    bool
		IsBanned   bool
	}

	users := []User{
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
	}

	hypercache.Set("key", users, 0)

	key, ok := hypercache.GetWithInfo("key")

	if !ok {
		panic("key not found")
	}

	fmt.Println("value", key.Value)
	fmt.Println("size", key.Size)

}

// `	fmt.Println("size", kate.Size)`
// the first method returns 43
