package main

import (
	"fmt"
	"time"

	"github.com/hyp3rd/hypercache"
	"github.com/hyp3rd/hypercache/backend"
)

func main() {
	config := hypercache.NewConfig[backend.InMemory]("in-memory")

	config.HyperCacheOptions = []hypercache.Option[backend.InMemory]{
		hypercache.WithEvictionInterval[backend.InMemory](0),
		hypercache.WithEvictionAlgorithm[backend.InMemory]("cawolfu"),
		hypercache.WithMaxCacheSize[backend.InMemory](37326),
	}

	config.InMemoryOptions = []backend.Option[backend.InMemory]{
		backend.WithCapacity[backend.InMemory](100000),
	}

	// Create a new HyperCache with a capacity of 10
	cache, err := hypercache.New(config)

	if err != nil {
		panic(err)
	}

	type User struct {
		Name       string
		Age        int
		LastAccess time.Time
		Pass       string
		Email      string
		Phone      string
		IsAdmin    bool
		IsGuest    bool
		IsBanned   bool
	}

	users := []User{
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John",
			Age:        30,
			LastAccess: time.Now(),
			Pass:       "123456",
			Email:      "jhon@example.com",
			Phone:      "123456789",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John1",
			Age:        31,
			LastAccess: time.Now(),
			Pass:       "1234567",
			Email:      "jhon1@example.com",
			Phone:      "1234567891011",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2John2John2John2John2John2John2John2John2John2John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
		{
			Name:       "John2",
			Age:        32,
			LastAccess: time.Now(),
			Pass:       "12345678",
			Email:      "jhon1@example.com",
			Phone:      "1234567891012",
			IsAdmin:    bool(true),
			IsGuest:    bool(false),
			IsBanned:   bool(false),
		},
	}

	for i := 0; i < 3; i++ {
		err = cache.Set(fmt.Sprintf("key-%d", i), users, 0)
		if err != nil {
			fmt.Println(err, "set", i)
		}
	}

	key, ok := cache.GetWithInfo("key-1")

	if ok {
		fmt.Println("value", key.Value)
		fmt.Println("size", key.Size)
	} else {
		fmt.Println("key not found")
	}
	fmt.Println(cache.Count())
	fmt.Println(cache.Allocation())
}

// `	fmt.Println("size", kate.Size)`
// the first method returns 43
