version: "0.2"
ignorePaths:
  - go.mod
  - go.sum
  - Makefile
  - .golangci-lint.yml
  - .golangci.yaml
  - .pre-commit-config.yaml
  - .project-settings.env
  - Dockerfile
  - .gitignore
  - .dockerignore
  - "*.pb.*"
  - "*.sql"
  - "*.svg"
  - docker/*
  - "*.excalidraw"
  - .vscode/*
  - azdo/pipelines/*
  - scripts/*
  - .github/workflows/*
  - .github/*
  - .idea/*
  - .DS_Store
  - "*.hcl"
  - "*.env"
  - "*.http"
  - compose.*.yaml
  - docs/mkdocs.yml
  - bench-*.txt
  - lint-*.txt
  - race-*.log
dictionaryDefinitions: []
dictionaries: []
words:
  - acks
  - ALPN
  - APITLS
  - APITLSCA
  - assertable
  - autosync
  - backpressure
  - baselining
  - benchmarkdist
  - benchmem
  - benchstat
  - benchtime
  - bitnami
  - bodyclose
  - bufbuild
  - buildx
  - cacheerrors
  - cachev
  - calledback
  - cand
  - CAWOLFU
  - Cbor
  - cespare
  - chans
  - cmap
  - Cmder
  - codacy
  - codegen
  - codemod
  - containedctx
  - contextcheck
  - cpuprofile
  - cret
  - cyclop
  - daixiang
  - Decr
  - dels
  - depguard
  - derr
  - disambiguator
  - distconfig
  - distroless
  - EDITMSG
  - elif
  - Equalf
  - errcheck
  - errp
  - ewrap
  - excalidraw
  - excludeonly
  - exhaustruct
  - Fanout
  - fasthttp
  - fatals
  - fctx
  - ferr
  - FLUSHALL
  - FLUSHDB
  - fontawesome
  - forcetypeassert
  - Fprintf
  - Fprintln
  - freqs
  - frontmatter
  - funlen
  - geomean
  - gerr
  - gitversion
  - GITVERSION
  - glightbox
  - goarch
  - gocache
  - goccy
  - gochecknoglobals
  - goconst
  - gofiber
  - GOFILES
  - gofmt
  - gofumpt
  - goimports
  - golangci
  - golines
  - GOPATH
  - goroutines
  - gosec
  - GOTOOLCHAIN
  - govulncheck
  - healthz
  - histogramcollector
  - HMAC
  - honnef
  - hostnames
  - hreq
  - httpauth
  - HTTPTLS
  - hypercache
  - Hyperd
  - idxs
  - Iface
  - ineff
  - inlinehilite
  - inmemory
  - intrange
  - ints
  - ireturn
  - Itemm
  - keyf
  - keypair
  - lamport
  - LFUDA
  - linenums
  - localmodule
  - logrus
  - longbridgeapp
  - mailtos
  - maxmemory
  - memprofile
  - Merkle
  - metricdata
  - metricnoop
  - mfinal
  - Mgmt
  - microbenchmark
  - mkdocs
  - mrand
  - mset
  - msgpack
  - mvdan
  - nestif
  - Newf
  - nilnil
  - nindent
  - noctx
  - noinlineerr
  - nolint
  - nolintlint
  - nonamedreturns
  - nonroot
  - nosec
  - NOVENDOR
  - oapi
  - paralleltest
  - Pipeliner
  - pluggability
  - podname
  - popd
  - Prealloc
  - productionization
  - protoc
  - pushd
  - pyenv
  - pygments
  - pymdownx
  - recvcheck
  - rediscluster
  - Redocly
  - repls
  - Repls
  - rerr
  - rootfs
  - sarif
  - sdkmetric
  - sectools
  - securego
  - sess
  - shamaton
  - shellcheck
  - skeys
  - SLRU
  - softprops
  - statefulset
  - staticcheck
  - stdlib
  - stretchr
  - strfnv
  - stringly
  - strs
  - subtest
  - subtests
  - superfences
  - sval
  - svcname
  - tasklist
  - thelper
  - toplevel
  - tparallel
  - tracetest
  - traefik
  - trunc
  - TTLMs
  - tunables
  - twemoji
  - ugorji
  - unconfigured
  - unmarshals
  - unpadded
  - unsharded
  - upserted
  - upserts
  - varnamelen
  - venv
  - vettool
  - vnode
  - vnodes
  - wrapcheck
  - Wrapf
  - xxhash
ignoreWords: []
import: []
